/**
 * xxd-amis-editor v1.1.2
 * build time: 2023-10-27
 * Copyright 2018-2023 @fex
 */

'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var amisEditorCore = require('amis-editor-core');
var audio = require('./feat/audio.svg.js');
var custom = require('./feat/custom.svg.js');
var each = require('./feat/each.svg.js');
var form = require('./feat/form.svg.js');
var nav = require('./feat/nav.svg.js');
var qrcode = require('./feat/qrcode.svg.js');
var service = require('./feat/service.svg.js');
var table = require('./feat/table.svg.js');
var tasks = require('./feat/tasks.svg.js');
var video = require('./feat/video.svg.js');
var wizard = require('./feat/wizard.svg.js');
var anchorNav = require('./container/anchor-nav.svg.js');
var collapse = require('./container/collapse.svg.js');
var container = require('./container/container.svg.js');
var switchContainer = require('./container/switch-container.svg.js');
var flexContainer = require('./container/flex-container.svg.js');
var formGroup = require('./container/form-group.svg.js');
var grid = require('./container/grid.svg.js');
var iframe = require('./container/iframe.svg.js');
var panel = require('./container/panel.svg.js');
var tableView = require('./container/table-view.svg.js');
var tabs = require('./container/tabs.svg.js');
var webComponent = require('./container/web-component.svg.js');
var tooltipWrapper = require('./container/tooltip-wrapper.svg.js');
var btnGroup = require('./btn/btn-group.svg.js');
var btnSelect = require('./btn/btn-select.svg.js');
var btnToolbar = require('./btn/btn-toolbar.svg.js');
var button = require('./btn/button.svg.js');
var dropdownBtn = require('./btn/dropdown-btn.svg.js');
var breadcrumb = require('./show/breadcrumb.svg.js');
var card = require('./show/card.svg.js');
var cards = require('./show/cards.svg.js');
var carousel = require('./show/carousel.svg.js');
var chart = require('./show/chart.svg.js');
var code = require('./show/code.svg.js');
var date = require('./show/date.svg.js');
var datetime = require('./show/datetime.svg.js');
var time = require('./show/time.svg.js');
var image = require('./show/image.svg.js');
var images = require('./show/images.svg.js');
var list = require('./show/list.svg.js');
var log = require('./show/log.svg.js');
var mapping = require('./show/mapping.svg.js');
var avatar = require('./show/avatar.svg.js');
var sparkline = require('./show/sparkline.svg.js');
var progress = require('./show/progress.svg.js');
var jsonView = require('./show/json-view.svg.js');
var markdown = require('./show/markdown.svg.js');
var steps = require('./show/steps.svg.js');
var status = require('./show/status.svg.js');
var plain = require('./show/plain.svg.js');
var URL = require('./show/URL.svg.js');
var chainedSelect = require('./form/chained-select.svg.js');
var checkbox = require('./form/checkbox.svg.js');
var checkboxes = require('./form/checkboxes.svg.js');
var combo = require('./form/combo.svg.js');
var conditionBuilder = require('./form/condition-builder.svg.js');
var diffEditor = require('./form/diff-editor.svg.js');
var editor = require('./form/editor.svg.js');
var hidden = require('./form/hidden.svg.js');
var inputCity = require('./form/input-city.svg.js');
var inputColor = require('./form/input-color.svg.js');
var inputTimeRange = require('./form/input-time-range.svg.js');
var inputDateRange = require('./form/input-date-range.svg.js');
var inputMonthRange = require('./form/input-month-range.svg.js');
var inputQuarterRange = require('./form/input-quarter-range.svg.js');
var inputDate = require('./form/input-date.svg.js');
var inputDatetime = require('./form/input-datetime.svg.js');
var inputEmail = require('./form/input-email.svg.js');
var inputExcel = require('./form/input-excel.svg.js');
var inputFile = require('./form/input-file.svg.js');
var inputGroup = require('./form/input-group.svg.js');
var inputImage = require('./form/input-image.svg.js');
var inputKv = require('./form/input-kv.svg.js');
var inputNumber = require('./form/input-number.svg.js');
var inputPassword = require('./form/input-password.svg.js');
var inputRange = require('./form/input-range.svg.js');
var inputRating = require('./form/input-rating.svg.js');
var inputRepeat = require('./form/input-repeat.svg.js');
var inputRichText = require('./form/input-rich-text.svg.js');
var inputTag = require('./form/input-tag.svg.js');
var inputText = require('./form/input-text.svg.js');
var inputTime = require('./form/input-time.svg.js');
var inputTree = require('./form/input-tree.svg.js');
var inputUrl = require('./form/input-url.svg.js');
var inputYear = require('./form/input-year.svg.js');
var listSelect = require('./form/list-select.svg.js');
var locationPicker = require('./form/location-picker.svg.js');
var matrixCheckboxes = require('./form/matrix-checkboxes.svg.js');
var month = require('./form/month.svg.js');
var nestedSelect = require('./form/nested-select.svg.js');
var picker = require('./form/picker.svg.js');
var quarter = require('./form/quarter.svg.js');
var radios = require('./form/radios.svg.js');
var select = require('./form/select.svg.js');
var _static = require('./form/static.svg.js');
var subForm = require('./form/sub-form.svg.js');
var _switch = require('./form/switch.svg.js');
var tabsTransfer = require('./form/tabs-transfer.svg.js');
var textarea = require('./form/textarea.svg.js');
var transfer = require('./form/transfer.svg.js');
var treeSelect = require('./form/tree-select.svg.js');
var uuid = require('./form/uuid.svg.js');
var formula = require('./form/formula.svg.js');
var inputArray = require('./form/inputArray.svg.js');
var propertySheet = require('./other/property-sheet.svg.js');
var tooltip = require('./other/tooltip.svg.js');
var divider = require('./other/divider.svg.js');
var layoutAbsolute = require('./layout/layout-absolute.svg.js');
var layoutFixed = require('./layout/layout-fixed.svg.js');
var layout1with2 = require('./layout/layout-1with2.svg.js');
var layout2cols = require('./layout/layout-2cols.svg.js');
var layout2row = require('./layout/layout-2row.svg.js');
var layout2with1 = require('./layout/layout-2with1.svg.js');
var layout3cols = require('./layout/layout-3cols.svg.js');
var layout3row = require('./layout/layout-3row.svg.js');
var layoutFull = require('./layout/layout-full.svg.js');
var layout12 = require('./layout/layout1-2.svg.js');
var layout21 = require('./layout/layout2-1.svg.js');
var layout31 = require('./layout/layout3-1.svg.js');
var layout32 = require('./layout/layout3-2.svg.js');
var layoutFreeContainer = require('./layout/layout-free-container.svg.js');
var layoutFixedTop = require('./layout/layout-fixed-top.svg.js');
var _fx = require('./other/_fx.svg.js');
var fx = require('./other/fx.svg.js');
var block = require('./display/block.svg.js');
var inline = require('./display/inline.svg.js');
var inlineBlock = require('./display/inline-block.svg.js');
var flex = require('./display/flex.svg.js');
var drow = require('./display/drow.svg.js');
var dcolumn = require('./display/dcolumn.svg.js');
var drowReverse = require('./display/drowReverse.svg.js');
var dcolumnReverse = require('./display/dcolumnReverse.svg.js');
var aFlexStart = require('./display/aFlexStart.svg.js');
var aCenter = require('./display/aCenter.svg.js');
var aFlexEnd = require('./display/aFlexEnd.svg.js');
var aStretch = require('./display/aStretch.svg.js');
var aBaseline = require('./display/aBaseline.svg.js');
var jFlexStart = require('./display/jFlexStart.svg.js');
var jCenter = require('./display/jCenter.svg.js');
var jFlexEnd = require('./display/jFlexEnd.svg.js');
var jSpaceBetween = require('./display/jSpaceBetween.svg.js');
var jSpaceAround = require('./display/jSpaceAround.svg.js');
var css = require('./theme/css.svg.js');
var columnSetting = require('./crud/column-setting.svg.js');
var columnDelete = require('./crud/column-delete.svg.js');
var columnAdd = require('./crud/column-add.svg.js');
var shareLink = require('./crud/share-link.svg.js');

// 功能类组件 icon x 11
amisEditorCore.registerIcon('audio-plugin', audio["default"]);
amisEditorCore.registerIcon('custom-plugin', custom["default"]);
amisEditorCore.registerIcon('each-plugin', each["default"]);
amisEditorCore.registerIcon('form-plugin', form["default"]);
amisEditorCore.registerIcon('nav-plugin', nav["default"]);
amisEditorCore.registerIcon('qrcode-plugin', qrcode["default"]);
amisEditorCore.registerIcon('service-plugin', service["default"]);
amisEditorCore.registerIcon('table-plugin', table["default"]);
amisEditorCore.registerIcon('tasks-plugin', tasks["default"]);
amisEditorCore.registerIcon('video-plugin', video["default"]);
amisEditorCore.registerIcon('wizard-plugin', wizard["default"]);
// 容器类组件 icon x 10
amisEditorCore.registerIcon('anchor-nav-plugin', anchorNav["default"]);
amisEditorCore.registerIcon('collapse-plugin', collapse["default"]);
amisEditorCore.registerIcon('flex-container-plugin', flexContainer["default"]);
amisEditorCore.registerIcon('container-plugin', container["default"]);
amisEditorCore.registerIcon('switch-container-plugin', switchContainer["default"]);
amisEditorCore.registerIcon('form-group-plugin', formGroup["default"]);
amisEditorCore.registerIcon('panel-plugin', panel["default"]);
amisEditorCore.registerIcon('grid-plugin', grid["default"]);
amisEditorCore.registerIcon('iframe-plugin', iframe["default"]);
amisEditorCore.registerIcon('table-view-plugin', tableView["default"]);
amisEditorCore.registerIcon('tabs-plugin', tabs["default"]);
amisEditorCore.registerIcon('web-component-plugin', webComponent["default"]);
amisEditorCore.registerIcon('tooltip-wrapper-plugin', tooltipWrapper["default"]);
// 按钮类组件 icon x5
amisEditorCore.registerIcon('btn-group-plugin', btnGroup["default"]);
amisEditorCore.registerIcon('btn-select-plugin', btnSelect["default"]);
amisEditorCore.registerIcon('btn-toolbar-plugin', btnToolbar["default"]);
amisEditorCore.registerIcon('button-plugin', button["default"]);
amisEditorCore.registerIcon('dropdown-btn-plugin', dropdownBtn["default"]);
// 展示类组件 icon x 23
amisEditorCore.registerIcon('breadcrumb-plugin', breadcrumb["default"]);
amisEditorCore.registerIcon('card-plugin', card["default"]);
amisEditorCore.registerIcon('cards-plugin', cards["default"]);
amisEditorCore.registerIcon('carousel-plugin', carousel["default"]);
amisEditorCore.registerIcon('chart-plugin', chart["default"]);
amisEditorCore.registerIcon('code-plugin', code["default"]);
amisEditorCore.registerIcon('date-plugin', date["default"]);
amisEditorCore.registerIcon('datetime-plugin', datetime["default"]);
amisEditorCore.registerIcon('time-plugin', time["default"]);
amisEditorCore.registerIcon('image-plugin', image["default"]);
amisEditorCore.registerIcon('images-plugin', images["default"]);
amisEditorCore.registerIcon('list-plugin', list["default"]);
amisEditorCore.registerIcon('log-plugin', log["default"]);
amisEditorCore.registerIcon('mapping-plugin', mapping["default"]);
amisEditorCore.registerIcon('sparkline-plugin', sparkline["default"]);
amisEditorCore.registerIcon('avatar-plugin', avatar["default"]);
amisEditorCore.registerIcon('progress-plugin', progress["default"]);
amisEditorCore.registerIcon('json-view-plugin', jsonView["default"]);
amisEditorCore.registerIcon('markdown-plugin', markdown["default"]);
amisEditorCore.registerIcon('steps-plugin', steps["default"]);
amisEditorCore.registerIcon('status-plugin', status["default"]);
amisEditorCore.registerIcon('plain-plugin', plain["default"]);
amisEditorCore.registerIcon('url-plugin', URL["default"]);
// 表单类组件 icon x 53
amisEditorCore.registerIcon('chained-select-plugin', chainedSelect["default"]);
amisEditorCore.registerIcon('checkbox-plugin', checkbox["default"]);
amisEditorCore.registerIcon('checkboxes-plugin', checkboxes["default"]);
amisEditorCore.registerIcon('combo-plugin', combo["default"]);
amisEditorCore.registerIcon('condition-builder-plugin', conditionBuilder["default"]);
amisEditorCore.registerIcon('diff-editor-plugin', diffEditor["default"]);
amisEditorCore.registerIcon('editor-plugin', editor["default"]);
amisEditorCore.registerIcon('hidden-plugin', hidden["default"]);
amisEditorCore.registerIcon('input-city-plugin', inputCity["default"]);
amisEditorCore.registerIcon('input-color-plugin', inputColor["default"]);
amisEditorCore.registerIcon('input-date-range-plugin', inputDateRange["default"]);
amisEditorCore.registerIcon('input-date-plugin', inputDate["default"]);
amisEditorCore.registerIcon('input-datetime-plugin', inputDatetime["default"]);
amisEditorCore.registerIcon('input-email-plugin', inputEmail["default"]);
amisEditorCore.registerIcon('input-excel-plugin', inputExcel["default"]);
amisEditorCore.registerIcon('input-file-plugin', inputFile["default"]);
amisEditorCore.registerIcon('input-group-plugin', inputGroup["default"]);
amisEditorCore.registerIcon('input-image-plugin', inputImage["default"]);
amisEditorCore.registerIcon('input-kv-plugin', inputKv["default"]);
amisEditorCore.registerIcon('input-month-range-plugin', inputMonthRange["default"]);
amisEditorCore.registerIcon('input-number-plugin', inputNumber["default"]);
amisEditorCore.registerIcon('input-password-plugin', inputPassword["default"]);
amisEditorCore.registerIcon('input-quarter-range-plugin', inputQuarterRange["default"]);
amisEditorCore.registerIcon('input-range-plugin', inputRange["default"]);
amisEditorCore.registerIcon('input-rating-plugin', inputRating["default"]);
amisEditorCore.registerIcon('input-repeat-plugin', inputRepeat["default"]);
amisEditorCore.registerIcon('input-rich-text-plugin', inputRichText["default"]);
amisEditorCore.registerIcon('input-tag-plugin', inputTag["default"]);
amisEditorCore.registerIcon('input-text-plugin', inputText["default"]);
amisEditorCore.registerIcon('input-time-range-plugin', inputTimeRange["default"]);
amisEditorCore.registerIcon('input-time-plugin', inputTime["default"]);
amisEditorCore.registerIcon('input-tree-plugin', inputTree["default"]);
amisEditorCore.registerIcon('input-url-plugin', inputUrl["default"]);
amisEditorCore.registerIcon('input-year-plugin', inputYear["default"]);
amisEditorCore.registerIcon('list-select-plugin', listSelect["default"]);
amisEditorCore.registerIcon('location-picker-plugin', locationPicker["default"]);
amisEditorCore.registerIcon('matrix-checkboxes-plugin', matrixCheckboxes["default"]);
amisEditorCore.registerIcon('month-plugin', month["default"]);
amisEditorCore.registerIcon('nested-select-plugin', nestedSelect["default"]);
amisEditorCore.registerIcon('picker-plugin', picker["default"]);
amisEditorCore.registerIcon('quarter-plugin', quarter["default"]);
amisEditorCore.registerIcon('radios-plugin', radios["default"]);
amisEditorCore.registerIcon('search-box-plugin', select["default"]);
amisEditorCore.registerIcon('select-plugin', select["default"]);
amisEditorCore.registerIcon('static-plugin', _static["default"]);
amisEditorCore.registerIcon('sub-form-plugin', subForm["default"]);
amisEditorCore.registerIcon('switch-plugin', _switch["default"]);
amisEditorCore.registerIcon('tabs-transfer-plugin', tabsTransfer["default"]);
amisEditorCore.registerIcon('textarea-plugin', textarea["default"]);
amisEditorCore.registerIcon('transfer-plugin', transfer["default"]);
amisEditorCore.registerIcon('tree-select-plugin', treeSelect["default"]);
amisEditorCore.registerIcon('uuid-plugin', uuid["default"]);
amisEditorCore.registerIcon('input-array-plugin', inputArray["default"]); // 暂时没用上
amisEditorCore.registerIcon('formula-plugin', formula["default"]);
// 其他类组件 icon
amisEditorCore.registerIcon('property-sheet-plugin', propertySheet["default"]);
amisEditorCore.registerIcon('tooltip-plugin', tooltip["default"]);
amisEditorCore.registerIcon('divider-plugin', divider["default"]);
// 常见布局组件 icon x 13
amisEditorCore.registerIcon('layout-absolute-plugin', layoutAbsolute["default"]);
amisEditorCore.registerIcon('layout-fixed-plugin', layoutFixed["default"]);
amisEditorCore.registerIcon('layout-1with2-plugin', layout1with2["default"]);
amisEditorCore.registerIcon('layout-2cols-plugin', layout2cols["default"]);
amisEditorCore.registerIcon('layout-2row-plugin', layout2row["default"]);
amisEditorCore.registerIcon('layout-2with1-plugin', layout2with1["default"]);
amisEditorCore.registerIcon('layout-3cols-plugin', layout3cols["default"]);
amisEditorCore.registerIcon('layout-3row-plugin', layout3row["default"]);
amisEditorCore.registerIcon('layout-full-plugin', layoutFull["default"]);
amisEditorCore.registerIcon('layout-1-2-plugin', layout12["default"]);
amisEditorCore.registerIcon('layout-2-1-plugin', layout21["default"]);
amisEditorCore.registerIcon('layout-3-1-plugin', layout31["default"]);
amisEditorCore.registerIcon('layout-3-2-plugin', layout32["default"]);
amisEditorCore.registerIcon('layout-free-container', layoutFreeContainer["default"]);
amisEditorCore.registerIcon('layout-fixed-top', layoutFixedTop["default"]);
amisEditorCore.registerIcon('input-add-fx', _fx["default"]);
amisEditorCore.registerIcon('input-fx', fx["default"]);
// 属性配置面板/显示类型
amisEditorCore.registerIcon('inline-display', inline["default"]);
amisEditorCore.registerIcon('inline-block-display', inlineBlock["default"]);
amisEditorCore.registerIcon('block-display', block["default"]);
amisEditorCore.registerIcon('flex-display', flex["default"]);
// 属性配置面板/flex相关配置icon
amisEditorCore.registerIcon('drow', drow["default"]);
amisEditorCore.registerIcon('dcolumn', dcolumn["default"]);
amisEditorCore.registerIcon('drowReverse', drowReverse["default"]);
amisEditorCore.registerIcon('dcolumnReverse', dcolumnReverse["default"]);
amisEditorCore.registerIcon('aFlexStart', aFlexStart["default"]);
amisEditorCore.registerIcon('aCenter', aCenter["default"]);
amisEditorCore.registerIcon('aFlexEnd', aFlexEnd["default"]);
amisEditorCore.registerIcon('aStretch', aStretch["default"]);
amisEditorCore.registerIcon('aBaseline', aBaseline["default"]);
amisEditorCore.registerIcon('jFlexStart', jFlexStart["default"]);
amisEditorCore.registerIcon('jCenter', jCenter["default"]);
amisEditorCore.registerIcon('jFlexEnd', jFlexEnd["default"]);
amisEditorCore.registerIcon('jSpaceBetween', jSpaceBetween["default"]);
amisEditorCore.registerIcon('jSpaceAround', jSpaceAround["default"]);
// 主题
amisEditorCore.registerIcon('theme-css', css["default"]);
// CRUD相关
amisEditorCore.registerIcon('column-setting', columnSetting["default"]);
amisEditorCore.registerIcon('column-delete', columnDelete["default"]);
amisEditorCore.registerIcon('column-add', columnAdd["default"]);
amisEditorCore.registerIcon('share-link', shareLink["default"]);

Object.defineProperty(exports, 'Icon', {
	enumerable: true,
	get: function () { return amisEditorCore.Icon; }
});
window.amisEditorVersionInfo={version:'1.1.2',buildTime:'2023-10-27'};
