/**
 * xxd-amis-editor v1.1.2
 * build time: 2023-10-27
 * Copyright 2018-2023 @fex
 */

'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

require('amis');
require('./locale/en-US.js');
require('./locale/zh-CN.js');
var amisEditorCore = require('amis-editor-core');
var constants = require('./builder/constants.js');
var utils = require('./builder/utils.js');
var DSBuilder = require('./builder/DSBuilder.js');
var DSBuilderManager = require('./builder/DSBuilderManager.js');
require('./builder/ApiDSBuilder.js');
require('./tpl/common.js');
require('./tpl/remark.js');
require('./tpl/horizontal.js');
require('./tpl/api.js');
require('./tpl/options.js');
require('./tpl/validations.js');
require('./tpl/style.js');
require('./tpl/layout.js');
var Flex = require('./plugin/Flex.js');
var Grid = require('./plugin/Grid.js');
var Container = require('./plugin/Container.js');
require('./plugin/Layout/Layout_free_container.js');
require('./plugin/Layout/Layout_sorption_container.js');
require('./plugin/Layout/Layout_fixed.js');
var CollapseGroup = require('./plugin/CollapseGroup.js');
var Panel = require('./plugin/Panel.js');
var Tabs = require('./plugin/Tabs.js');
var SwitchContainer = require('./plugin/SwitchContainer.js');
var CRUD = require('./plugin/CRUD.js');
var CRUDTable = require('./plugin/CRUD2/CRUDTable.js');
var utils$1 = require('./plugin/CRUD2/utils.js');
var Form = require('./plugin/Form/Form.js');
var Service = require('./plugin/Service.js');
var InputText = require('./plugin/Form/InputText.js');
var Textarea = require('./plugin/Form/Textarea.js');
var InputNumber = require('./plugin/Form/InputNumber.js');
var Select = require('./plugin/Form/Select.js');
var NestedSelect = require('./plugin/Form/NestedSelect.js');
var ChainedSelect = require('./plugin/Form/ChainedSelect.js');
var DropDownButton = require('./plugin/DropDownButton.js');
var Checkboxes = require('./plugin/Form/Checkboxes.js');
var Radios = require('./plugin/Form/Radios.js');
var Checkbox = require('./plugin/Form/Checkbox.js');
var InputDate = require('./plugin/Form/InputDate.js');
var InputDateRange = require('./plugin/Form/InputDateRange.js');
var InputFile = require('./plugin/Form/InputFile.js');
var InputImage = require('./plugin/Form/InputImage.js');
var InputExcel = require('./plugin/Form/InputExcel.js');
var InputTree = require('./plugin/Form/InputTree.js');
var InputTag = require('./plugin/Form/InputTag.js');
var ListSelect = require('./plugin/Form/ListSelect.js');
var ButtonGroupSelect = require('./plugin/Form/ButtonGroupSelect.js');
var ButtonToolbar = require('./plugin/Form/ButtonToolbar.js');
var Picker = require('./plugin/Form/Picker.js');
var Switch = require('./plugin/Form/Switch.js');
var InputRange = require('./plugin/Form/InputRange.js');
var InputRating = require('./plugin/Form/InputRating.js');
var InputCity = require('./plugin/Form/InputCity.js');
var Transfer = require('./plugin/Form/Transfer.js');
var TabsTransfer = require('./plugin/Form/TabsTransfer.js');
var InputColor = require('./plugin/Form/InputColor.js');
var ConditionBuilder = require('./plugin/Form/ConditionBuilder.js');
var FieldSet = require('./plugin/Form/FieldSet.js');
var Combo = require('./plugin/Form/Combo.js');
var InputGroup = require('./plugin/Form/InputGroup.js');
var InputTable = require('./plugin/Form/InputTable.js');
var MatrixCheckboxes = require('./plugin/Form/MatrixCheckboxes.js');
var InputRichText = require('./plugin/Form/InputRichText.js');
var DiffEditor = require('./plugin/Form/DiffEditor.js');
var CodeEditor = require('./plugin/Form/CodeEditor.js');
var SearchBox = require('./plugin/SearchBox.js');
var InputKV = require('./plugin/Form/InputKV.js');
var InputRepeat = require('./plugin/Form/InputRepeat.js');
var UUID = require('./plugin/Form/UUID.js');
var LocationPicker = require('./plugin/Form/LocationPicker.js');
var InputSubForm = require('./plugin/Form/InputSubForm.js');
var Hidden = require('./plugin/Form/Hidden.js');
var Button = require('./plugin/Button.js');
var ButtonGroup = require('./plugin/ButtonGroup.js');
var Nav = require('./plugin/Nav.js');
var AnchorNav = require('./plugin/AnchorNav.js');
var TooltipWrapper = require('./plugin/TooltipWrapper.js');
var Alert = require('./plugin/Alert.js');
var Wizard = require('./plugin/Wizard.js');
var TableView = require('./plugin/TableView.js');
var WebComponent = require('./plugin/WebComponent.js');
var Audio = require('./plugin/Audio.js');
var Video = require('./plugin/Video.js');
var Custom = require('./plugin/Custom.js');
var Tasks = require('./plugin/Tasks.js');
var Each = require('./plugin/Each.js');
var Property = require('./plugin/Property.js');
var IFrame = require('./plugin/IFrame.js');
var QRCode = require('./plugin/QRCode.js');
var Tpl = require('./plugin/Tpl.js');
var Icon = require('./plugin/Icon.js');
var Link = require('./plugin/Link.js');
var List = require('./plugin/List.js');
var List2 = require('./plugin/List2.js');
var Mapping = require('./plugin/Mapping.js');
var Avatar = require('./plugin/Avatar.js');
var Card = require('./plugin/Card.js');
var Card2 = require('./plugin/Card2.js');
var Cards = require('./plugin/Cards.js');
var Table = require('./plugin/Table.js');
var Table2 = require('./plugin/Table2.js');
var TableCell2 = require('./plugin/TableCell2.js');
var Chart = require('./plugin/Chart.js');
var Sparkline = require('./plugin/Sparkline.js');
var Carousel = require('./plugin/Carousel.js');
var Image = require('./plugin/Image.js');
var Images = require('./plugin/Images.js');
var Time = require('./plugin/Time.js');
var Date = require('./plugin/Date.js');
var Datetime = require('./plugin/Datetime.js');
var Tag = require('./plugin/Tag.js');
var Json = require('./plugin/Json.js');
var Progress = require('./plugin/Progress.js');
var Status = require('./plugin/Status.js');
var Steps = require('./plugin/Steps.js');
var Timeline = require('./plugin/Timeline.js');
var Divider = require('./plugin/Divider.js');
var CodeView = require('./plugin/CodeView.js');
var Markdown = require('./plugin/Markdown.js');
var Collapse = require('./plugin/Collapse.js');
var OfficeViewer = require('./plugin/OfficeViewer.js');
var Log = require('./plugin/Log.js');
var Action = require('./plugin/Others/Action.js');
var TableCell = require('./plugin/Others/TableCell.js');
var InputArray = require('./plugin/Form/InputArray.js');
var Control = require('./plugin/Form/Control.js');
var InputDateTime = require('./plugin/Form/InputDateTime.js');
var InputDateTimeRange = require('./plugin/Form/InputDateTimeRange.js');
var InputEmail = require('./plugin/Form/InputEmail.js');
var Formula = require('./plugin/Form/Formula.js');
var Group = require('./plugin/Form/Group.js');
var Item = require('./plugin/Form/Item.js');
var InputMonth = require('./plugin/Form/InputMonth.js');
var InputMonthRange = require('./plugin/Form/InputMonthRange.js');
var InputPassword = require('./plugin/Form/InputPassword.js');
var InputQuarter = require('./plugin/Form/InputQuarter.js');
var InputQuarterRange = require('./plugin/Form/InputQuarterRange.js');
var Static = require('./plugin/Form/Static.js');
var InputTime = require('./plugin/Form/InputTime.js');
var InputTimeRange = require('./plugin/Form/InputTimeRange.js');
var TreeSelect = require('./plugin/Form/TreeSelect.js');
var InputURL = require('./plugin/Form/InputURL.js');
var InputYear = require('./plugin/Form/InputYear.js');
var InputYearRange = require('./plugin/Form/InputYearRange.js');
var Breadcrumb = require('./plugin/Breadcrumb.js');
var CustomRegion = require('./plugin/CustomRegion.js');
var Dialog = require('./plugin/Dialog.js');
var Drawer = require('./plugin/Drawer.js');
var HBox = require('./plugin/HBox.js');
var ListItem = require('./plugin/ListItem.js');
var Operation = require('./plugin/Operation.js');
var Page = require('./plugin/Page.js');
var Pagination = require('./plugin/Pagination.js');
var Plain = require('./plugin/Plain.js');
var Reset = require('./plugin/Reset.js');
var Submit = require('./plugin/Submit.js');
var Wrapper = require('./plugin/Wrapper.js');
var ColumnToggler = require('./plugin/ColumnToggler.js');
require('./renderer/OptionControl.js');
require('./renderer/NavSourceControl.js');
require('./renderer/NavBadgeControl.js');
require('./renderer/NavDefaultActive.js');
require('./renderer/MapSourceControl.js');
require('./renderer/TimelineItemControl.js');
require('./renderer/APIControl.js');
require('./renderer/APIAdaptorControl.js');
require('./renderer/ValidationControl.js');
require('./renderer/ValidationItem.js');
require('./renderer/SwitchMoreControl.js');
require('./renderer/StatusControl.js');
require('./renderer/FormulaControl.js');
require('./renderer/ExpressionFormulaControl.js');
require('./renderer/textarea-formula/TextareaFormulaControl.js');
require('./renderer/TplFormulaControl.js');
require('./renderer/DateShortCutControl.js');
require('./renderer/BadgeControl.js');
require('./renderer/style-control/BoxModel.js');
require('./renderer/style-control/Font.js');
require('./renderer/style-control/Border.js');
require('./renderer/style-control/BoxShadow.js');
require('./renderer/style-control/Background.js');
require('./renderer/style-control/Display.js');
require('./renderer/style-control/InsetBoxModel.js');
require('./renderer/RangePartsControl.js');
require('./renderer/DataBindingControl.js');
require('./renderer/DataMappingControl.js');
require('./renderer/DataPickerControl.js');
require('./renderer/FeatureControl.js');
require('./renderer/event-control/index.js');
require('./renderer/TreeOptionControl.js');
require('./renderer/TransferTableControl.js');
require('./renderer/style-control/ThemeCssCode.js');
require('./renderer/ButtonGroupControl.js');
require('./renderer/FlexSettingControl.js');
require('./renderer/FieldSetting.js');
require('./renderer/TableColumnWidthControl.js');
require('./renderer/crud2-control/CRUDColumnControl.js');
require('./renderer/crud2-control/CRUDToolbarControl.js');
require('./renderer/crud2-control/CRUDFiltersControl.js');
require('./renderer/InputRangeValueControl.js');
require('./renderer/FunctionEditorControl.js');
require('./renderer/ListItemControl.js');
require('amis-theme-editor/lib/locale/zh-CN');
require('amis-theme-editor/lib/locale/en-US');
require('amis-theme-editor/lib/renderers/Border');
require('amis-theme-editor/lib/renderers/ColorPicker');
require('amis-theme-editor/lib/renderers/Font');
require('amis-theme-editor/lib/renderers/PaddingAndMargin');
require('amis-theme-editor/lib/renderers/Radius');
require('amis-theme-editor/lib/renderers/Shadow');
require('amis-theme-editor/lib/renderers/Size');
require('amis-theme-editor/lib/renderers.css');
var BaseControl = require('./component/BaseControl.js');
require('./icons/index.js');



Object.defineProperty(exports, 'Icon', {
	enumerable: true,
	get: function () { return amisEditorCore.Icon; }
});
exports.ApiCenterDSBuilderKey = constants.ApiCenterDSBuilderKey;
exports.ApiDSBuilderKey = constants.ApiDSBuilderKey;
Object.defineProperty(exports, 'DSBehavior', {
	enumerable: true,
	get: function () { return constants.DSBehavior; }
});
exports.DSFeature = constants.DSFeature;
Object.defineProperty(exports, 'DSFeatureEnum', {
	enumerable: true,
	get: function () { return constants.DSFeatureEnum; }
});
exports.DSFeatureList = constants.DSFeatureList;
Object.defineProperty(exports, 'DSGrain', {
	enumerable: true,
	get: function () { return constants.DSGrain; }
});
exports.FormOperatorMap = constants.FormOperatorMap;
exports.ModelDSBuilderKey = constants.ModelDSBuilderKey;
exports.displayType2inputType = utils.displayType2inputType;
exports.getFeatLabelByKey = utils.getFeatLabelByKey;
exports.getFeatValueByKey = utils.getFeatValueByKey;
exports.traverseSchemaDeep = utils.traverseSchemaDeep;
exports.DSBuilder = DSBuilder.DSBuilder;
exports.builderFactory = DSBuilder.builderFactory;
exports.registerDSBuilder = DSBuilder.registerDSBuilder;
exports.DSBuilderManager = DSBuilderManager.DSBuilderManager;
exports.FlexPlugin = Flex.FlexPlugin;
exports.GridPlugin = Grid.GridPlugin;
exports.ContainerPlugin = Container.ContainerPlugin;
exports.CollapseGroupPlugin = CollapseGroup.CollapseGroupPlugin;
exports.PanelPlugin = Panel.PanelPlugin;
exports.TabsPlugin = Tabs.TabsPlugin;
exports.SwitchContainerPlugin = SwitchContainer.SwitchContainerPlugin;
exports.CRUDPlugin = CRUD.CRUDPlugin;
exports.CRUDTablePlugin = CRUDTable.CRUDTablePlugin;
exports.addSchema2Toolbar = utils$1.addSchema2Toolbar;
exports.deepRemove = utils$1.deepRemove;
exports.findAndUpdate = utils$1.findAndUpdate;
exports.findObj = utils$1.findObj;
exports.findSchema = utils$1.findSchema;
exports.FormPlugin = Form.FormPlugin;
exports.ServicePlugin = Service.ServicePlugin;
exports.TextControlPlugin = InputText.TextControlPlugin;
exports.TextareaControlPlugin = Textarea.TextareaControlPlugin;
exports.NumberControlPlugin = InputNumber.NumberControlPlugin;
exports.SelectControlPlugin = Select.SelectControlPlugin;
exports.NestedSelectControlPlugin = NestedSelect.NestedSelectControlPlugin;
exports.ChainedSelectControlPlugin = ChainedSelect.ChainedSelectControlPlugin;
exports.DropDownButtonPlugin = DropDownButton.DropDownButtonPlugin;
exports.CheckboxesControlPlugin = Checkboxes.CheckboxesControlPlugin;
exports.RadiosControlPlugin = Radios.RadiosControlPlugin;
exports.CheckboxControlPlugin = Checkbox.CheckboxControlPlugin;
exports.DateControlPlugin = InputDate.DateControlPlugin;
exports.DateRangeControlPlugin = InputDateRange.DateRangeControlPlugin;
exports.FileControlPlugin = InputFile.FileControlPlugin;
exports.ImageControlPlugin = InputImage.ImageControlPlugin;
exports.ExcelControlPlugin = InputExcel.ExcelControlPlugin;
exports.TreeControlPlugin = InputTree.TreeControlPlugin;
exports.TagControlPlugin = InputTag.TagControlPlugin;
exports.ListControlPlugin = ListSelect.ListControlPlugin;
exports.ButtonGroupControlPlugin = ButtonGroupSelect.ButtonGroupControlPlugin;
exports.ButtonToolbarControlPlugin = ButtonToolbar.ButtonToolbarControlPlugin;
exports.PickerControlPlugin = Picker.PickerControlPlugin;
exports.SwitchControlPlugin = Switch.SwitchControlPlugin;
exports.RangeControlPlugin = InputRange.RangeControlPlugin;
exports.RateControlPlugin = InputRating.RateControlPlugin;
exports.CityControlPlugin = InputCity.CityControlPlugin;
exports.TransferPlugin = Transfer.TransferPlugin;
exports.TabsTransferPlugin = TabsTransfer.TabsTransferPlugin;
exports.ColorControlPlugin = InputColor.ColorControlPlugin;
exports.ConditionBilderPlugin = ConditionBuilder.ConditionBilderPlugin;
exports.FieldSetControlPlugin = FieldSet.FieldSetControlPlugin;
exports.ComboControlPlugin = Combo.ComboControlPlugin;
exports.InputGroupControlPlugin = InputGroup.InputGroupControlPlugin;
exports.TableControlPlugin = InputTable.TableControlPlugin;
exports.MatrixControlPlugin = MatrixCheckboxes.MatrixControlPlugin;
exports.RichTextControlPlugin = InputRichText.RichTextControlPlugin;
exports.DiffEditorControlPlugin = DiffEditor.DiffEditorControlPlugin;
exports.CodeEditorControlPlugin = CodeEditor.CodeEditorControlPlugin;
exports.SearchBoxPlugin = SearchBox.SearchBoxPlugin;
exports.KVControlPlugin = InputKV.KVControlPlugin;
exports.RepeatControlPlugin = InputRepeat.RepeatControlPlugin;
exports.UUIDControlPlugin = UUID.UUIDControlPlugin;
exports.LocationControlPlugin = LocationPicker.LocationControlPlugin;
exports.SubFormControlPlugin = InputSubForm.SubFormControlPlugin;
exports.HiddenControlPlugin = Hidden.HiddenControlPlugin;
exports.ButtonPlugin = Button.ButtonPlugin;
exports.ButtonGroupPlugin = ButtonGroup.ButtonGroupPlugin;
exports.NavPlugin = Nav.NavPlugin;
exports.AnchorNavPlugin = AnchorNav.AnchorNavPlugin;
exports.TooltipWrapperPlugin = TooltipWrapper.TooltipWrapperPlugin;
exports.AlertPlugin = Alert.AlertPlugin;
exports.WizardPlugin = Wizard.WizardPlugin;
exports.TableViewPlugin = TableView.TableViewPlugin;
exports.WebComponentPlugin = WebComponent.WebComponentPlugin;
exports.AudioPlugin = Audio.AudioPlugin;
exports.VideoPlugin = Video.VideoPlugin;
exports.CustomPlugin = Custom.CustomPlugin;
exports.TasksPlugin = Tasks.TasksPlugin;
exports.EachPlugin = Each.EachPlugin;
exports.PropertyPlugin = Property.PropertyPlugin;
exports.IFramePlugin = IFrame.IFramePlugin;
exports.QRCodePlugin = QRCode.QRCodePlugin;
exports.TplPlugin = Tpl.TplPlugin;
exports.IconPlugin = Icon.IconPlugin;
exports.LinkPlugin = Link.LinkPlugin;
exports.ListPlugin = List.ListPlugin;
exports.List2Plugin = List2.List2Plugin;
exports.MappingPlugin = Mapping.MappingPlugin;
exports.AvatarPlugin = Avatar.AvatarPlugin;
exports.CardPlugin = Card.CardPlugin;
exports.Card2Plugin = Card2.Card2Plugin;
exports.CardsPlugin = Cards.CardsPlugin;
exports.TablePlugin = Table.TablePlugin;
exports.Table2Plugin = Table2.Table2Plugin;
exports.Table2RendererAction = Table2.Table2RendererAction;
exports.Table2RenderereEvent = Table2.Table2RenderereEvent;
exports.TableCell2Plugin = TableCell2.TableCell2Plugin;
exports.ChartPlugin = Chart.ChartPlugin;
exports.SparklinePlugin = Sparkline.SparklinePlugin;
exports.CarouselPlugin = Carousel.CarouselPlugin;
exports.ImagePlugin = Image.ImagePlugin;
exports.ImagesPlugin = Images.ImagesPlugin;
exports.TimePlugin = Time.TimePlugin;
exports.DatePlugin = Date.DatePlugin;
exports.DatetimePlugin = Datetime.DatetimePlugin;
exports.TagPlugin = Tag.TagPlugin;
exports.JsonPlugin = Json.JsonPlugin;
exports.ProgressPlugin = Progress.ProgressPlugin;
exports.StatusPlugin = Status.StatusPlugin;
exports.StepsPlugin = Steps.StepsPlugin;
exports.TimelinePlugin = Timeline.TimelinePlugin;
exports.DividerPlugin = Divider.DividerPlugin;
exports.CodeViewPlugin = CodeView.CodeViewPlugin;
exports.MarkdownPlugin = Markdown.MarkdownPlugin;
exports.CollapsePlugin = Collapse.CollapsePlugin;
exports.OfficeViewerPlugin = OfficeViewer.OfficeViewerPlugin;
exports.LogPlugin = Log.LogPlugin;
exports.ActionPlugin = Action.ActionPlugin;
exports.TableCellPlugin = TableCell.TableCellPlugin;
exports.ArrayControlPlugin = InputArray.ArrayControlPlugin;
exports.ControlPlugin = Control.ControlPlugin;
exports.DateTimeControlPlugin = InputDateTime.DateTimeControlPlugin;
exports.DateTimeRangeControlPlugin = InputDateTimeRange.DateTimeRangeControlPlugin;
exports.EmailControlPlugin = InputEmail.EmailControlPlugin;
exports.FormulaControlPlugin = Formula.FormulaControlPlugin;
exports.GroupControlPlugin = Group.GroupControlPlugin;
exports.ItemPlugin = Item.ItemPlugin;
exports.MonthControlPlugin = InputMonth.MonthControlPlugin;
exports.MonthRangeControlPlugin = InputMonthRange.MonthRangeControlPlugin;
exports.PasswordControlPlugin = InputPassword.PasswordControlPlugin;
exports.InputQuarterPlugin = InputQuarter.InputQuarterPlugin;
exports.QuarterRangePlugin = InputQuarterRange.QuarterRangePlugin;
exports.StaticControlPlugin = Static.StaticControlPlugin;
exports.TimeControlPlugin = InputTime.TimeControlPlugin;
exports.TimeRangeControlPlugin = InputTimeRange.TimeRangeControlPlugin;
exports.TreeSelectControlPlugin = TreeSelect.TreeSelectControlPlugin;
exports.URLControlPlugin = InputURL.URLControlPlugin;
exports.YearControlPlugin = InputYear.YearControlPlugin;
exports.YearRangeControlPlugin = InputYearRange.YearRangeControlPlugin;
exports.BreadcrumbPlugin = Breadcrumb.BreadcrumbPlugin;
exports.CustomRegionPlugin = CustomRegion.CustomPlugin;
exports.DialogPlugin = Dialog.DialogPlugin;
exports.InlineModal = Dialog.InlineModal;
exports.DrawerPlugin = Drawer.DrawerPlugin;
exports.HBoxPlugin = HBox.HBoxPlugin;
exports.ListItemPlugin = ListItem.ListItemPlugin;
exports.OperationPlugin = Operation.OperationPlugin;
exports.PagePlugin = Page.PagePlugin;
exports.PaginationPlugin = Pagination.PaginationPlugin;
exports.PlainPlugin = Plain.PlainPlugin;
exports.ResetPlugin = Reset.ResetPlugin;
exports.SubmitPlugin = Submit.SubmitPlugin;
exports.WrapperPlugin = Wrapper.WrapperPlugin;
exports.ColumnToggler = ColumnToggler.ColumnToggler;
exports.BUTTON_DEFAULT_ACTION = BaseControl.BUTTON_DEFAULT_ACTION;
exports.BaseLabelMark = BaseControl.BaseLabelMark;
exports.formItemControl = BaseControl.formItemControl;
exports.remarkTpl = BaseControl.remarkTpl;
Object.keys(amisEditorCore).forEach(function (k) {
	if (k !== 'default' && !exports.hasOwnProperty(k)) Object.defineProperty(exports, k, {
		enumerable: true,
		get: function () { return amisEditorCore[k]; }
	});
});
window.amisEditorVersionInfo={version:'1.1.2',buildTime:'2023-10-27'};
