/**
 * xxd-amis-editor v1.1.2
 * build time: 2023-10-27
 * Copyright 2018-2023 @fex
 */

import { registerIcon } from 'amis-editor-core';
export { Icon } from 'amis-editor-core';
import SvgAudio from './feat/audio.svg.js';
import SvgCustom from './feat/custom.svg.js';
import SvgEach from './feat/each.svg.js';
import SvgForm from './feat/form.svg.js';
import SvgNav from './feat/nav.svg.js';
import SvgQrcode from './feat/qrcode.svg.js';
import SvgService from './feat/service.svg.js';
import SvgTable from './feat/table.svg.js';
import SvgTasks from './feat/tasks.svg.js';
import SvgVideo from './feat/video.svg.js';
import SvgWizard from './feat/wizard.svg.js';
import SvgAnchorNav from './container/anchor-nav.svg.js';
import SvgCollapse from './container/collapse.svg.js';
import SvgContainer from './container/container.svg.js';
import SvgSwitchContainer from './container/switch-container.svg.js';
import SvgFlexContainer from './container/flex-container.svg.js';
import SvgFormGroup from './container/form-group.svg.js';
import SvgGrid from './container/grid.svg.js';
import SvgIframe from './container/iframe.svg.js';
import SvgPanel from './container/panel.svg.js';
import SvgTableView from './container/table-view.svg.js';
import SvgTabs from './container/tabs.svg.js';
import SvgWebComponent from './container/web-component.svg.js';
import SvgTooltipWrapper from './container/tooltip-wrapper.svg.js';
import SvgBtnGroup from './btn/btn-group.svg.js';
import SvgBtnSelect from './btn/btn-select.svg.js';
import SvgBtnToolbar from './btn/btn-toolbar.svg.js';
import SvgButton from './btn/button.svg.js';
import SvgDropdownBtn from './btn/dropdown-btn.svg.js';
import SvgBreadcrumb from './show/breadcrumb.svg.js';
import SvgCard from './show/card.svg.js';
import SvgCards from './show/cards.svg.js';
import SvgCarousel from './show/carousel.svg.js';
import SvgChart from './show/chart.svg.js';
import SvgCode from './show/code.svg.js';
import SvgDate from './show/date.svg.js';
import SvgDatetime from './show/datetime.svg.js';
import SvgTime from './show/time.svg.js';
import SvgImage from './show/image.svg.js';
import SvgImages from './show/images.svg.js';
import SvgList from './show/list.svg.js';
import SvgLog from './show/log.svg.js';
import SvgMapping from './show/mapping.svg.js';
import SvgAvatar from './show/avatar.svg.js';
import SvgSparkline from './show/sparkline.svg.js';
import SvgProgress from './show/progress.svg.js';
import SvgJsonView from './show/json-view.svg.js';
import SvgMarkdown from './show/markdown.svg.js';
import SvgSteps from './show/steps.svg.js';
import SvgStatus from './show/status.svg.js';
import SvgPlain from './show/plain.svg.js';
import SvgUrl from './show/URL.svg.js';
import SvgChainedSelect from './form/chained-select.svg.js';
import SvgCheckbox from './form/checkbox.svg.js';
import SvgCheckboxes from './form/checkboxes.svg.js';
import SvgCombo from './form/combo.svg.js';
import SvgConditionBuilder from './form/condition-builder.svg.js';
import SvgDiffEditor from './form/diff-editor.svg.js';
import SvgEditor from './form/editor.svg.js';
import SvgHidden from './form/hidden.svg.js';
import SvgInputCity from './form/input-city.svg.js';
import SvgInputColor from './form/input-color.svg.js';
import SvgInputTimeRange from './form/input-time-range.svg.js';
import SvgInputDateRange from './form/input-date-range.svg.js';
import SvgInputMonthRange from './form/input-month-range.svg.js';
import SvgInputQuarterRange from './form/input-quarter-range.svg.js';
import SvgInputDate from './form/input-date.svg.js';
import SvgInputDatetime from './form/input-datetime.svg.js';
import SvgInputEmail from './form/input-email.svg.js';
import SvgInputExcel from './form/input-excel.svg.js';
import SvgInputFile from './form/input-file.svg.js';
import SvgInputGroup from './form/input-group.svg.js';
import SvgInputImage from './form/input-image.svg.js';
import SvgInputKv from './form/input-kv.svg.js';
import SvgInputNumber from './form/input-number.svg.js';
import SvgInputPassword from './form/input-password.svg.js';
import SvgInputRange from './form/input-range.svg.js';
import SvgInputRating from './form/input-rating.svg.js';
import SvgInputRepeat from './form/input-repeat.svg.js';
import SvgInputRichText from './form/input-rich-text.svg.js';
import SvgInputTag from './form/input-tag.svg.js';
import SvgInputText from './form/input-text.svg.js';
import SvgInputTime from './form/input-time.svg.js';
import SvgInputTree from './form/input-tree.svg.js';
import SvgInputUrl from './form/input-url.svg.js';
import SvgInputYear from './form/input-year.svg.js';
import SvgListSelect from './form/list-select.svg.js';
import SvgLocationPicker from './form/location-picker.svg.js';
import SvgMatrixCheckboxes from './form/matrix-checkboxes.svg.js';
import SvgMonth from './form/month.svg.js';
import SvgNestedSelect from './form/nested-select.svg.js';
import SvgPicker from './form/picker.svg.js';
import SvgQuarter from './form/quarter.svg.js';
import SvgRadios from './form/radios.svg.js';
import SvgSelect from './form/select.svg.js';
import SvgStatic from './form/static.svg.js';
import SvgSubForm from './form/sub-form.svg.js';
import SvgSwitch from './form/switch.svg.js';
import SvgTabsTransfer from './form/tabs-transfer.svg.js';
import SvgTextarea from './form/textarea.svg.js';
import SvgTransfer from './form/transfer.svg.js';
import SvgTreeSelect from './form/tree-select.svg.js';
import SvgUuid from './form/uuid.svg.js';
import SvgFormula from './form/formula.svg.js';
import SvgInputArray from './form/inputArray.svg.js';
import SvgPropertySheet from './other/property-sheet.svg.js';
import SvgTooltip from './other/tooltip.svg.js';
import SvgDivider from './other/divider.svg.js';
import SvgLayoutAbsolute from './layout/layout-absolute.svg.js';
import SvgLayoutFixed from './layout/layout-fixed.svg.js';
import SvgLayout1With2 from './layout/layout-1with2.svg.js';
import SvgLayout2Cols from './layout/layout-2cols.svg.js';
import SvgLayout2Row from './layout/layout-2row.svg.js';
import SvgLayout2With1 from './layout/layout-2with1.svg.js';
import SvgLayout3Cols from './layout/layout-3cols.svg.js';
import SvgLayout3Row from './layout/layout-3row.svg.js';
import SvgLayoutFull from './layout/layout-full.svg.js';
import SvgLayout12 from './layout/layout1-2.svg.js';
import SvgLayout21 from './layout/layout2-1.svg.js';
import SvgLayout31 from './layout/layout3-1.svg.js';
import SvgLayout32 from './layout/layout3-2.svg.js';
import SvgLayoutFreeContainer from './layout/layout-free-container.svg.js';
import SvgLayoutFixedTop from './layout/layout-fixed-top.svg.js';
import SvgFx from './other/_fx.svg.js';
import SvgFx$1 from './other/fx.svg.js';
import SvgBlock from './display/block.svg.js';
import SvgInline from './display/inline.svg.js';
import SvgInlineBlock from './display/inline-block.svg.js';
import SvgFlex from './display/flex.svg.js';
import SvgDrow from './display/drow.svg.js';
import SvgDcolumn from './display/dcolumn.svg.js';
import SvgDrowReverse from './display/drowReverse.svg.js';
import SvgDcolumnReverse from './display/dcolumnReverse.svg.js';
import SvgAFlexStart from './display/aFlexStart.svg.js';
import SvgACenter from './display/aCenter.svg.js';
import SvgAFlexEnd from './display/aFlexEnd.svg.js';
import SvgAStretch from './display/aStretch.svg.js';
import SvgABaseline from './display/aBaseline.svg.js';
import SvgJFlexStart from './display/jFlexStart.svg.js';
import SvgJCenter from './display/jCenter.svg.js';
import SvgJFlexEnd from './display/jFlexEnd.svg.js';
import SvgJSpaceBetween from './display/jSpaceBetween.svg.js';
import SvgJSpaceAround from './display/jSpaceAround.svg.js';
import SvgCss from './theme/css.svg.js';
import SvgColumnSetting from './crud/column-setting.svg.js';
import SvgColumnDelete from './crud/column-delete.svg.js';
import SvgColumnAdd from './crud/column-add.svg.js';
import SvgShareLink from './crud/share-link.svg.js';

// 功能类组件 icon x 11
registerIcon('audio-plugin', SvgAudio);
registerIcon('custom-plugin', SvgCustom);
registerIcon('each-plugin', SvgEach);
registerIcon('form-plugin', SvgForm);
registerIcon('nav-plugin', SvgNav);
registerIcon('qrcode-plugin', SvgQrcode);
registerIcon('service-plugin', SvgService);
registerIcon('table-plugin', SvgTable);
registerIcon('tasks-plugin', SvgTasks);
registerIcon('video-plugin', SvgVideo);
registerIcon('wizard-plugin', SvgWizard);
// 容器类组件 icon x 10
registerIcon('anchor-nav-plugin', SvgAnchorNav);
registerIcon('collapse-plugin', SvgCollapse);
registerIcon('flex-container-plugin', SvgFlexContainer);
registerIcon('container-plugin', SvgContainer);
registerIcon('switch-container-plugin', SvgSwitchContainer);
registerIcon('form-group-plugin', SvgFormGroup);
registerIcon('panel-plugin', SvgPanel);
registerIcon('grid-plugin', SvgGrid);
registerIcon('iframe-plugin', SvgIframe);
registerIcon('table-view-plugin', SvgTableView);
registerIcon('tabs-plugin', SvgTabs);
registerIcon('web-component-plugin', SvgWebComponent);
registerIcon('tooltip-wrapper-plugin', SvgTooltipWrapper);
// 按钮类组件 icon x5
registerIcon('btn-group-plugin', SvgBtnGroup);
registerIcon('btn-select-plugin', SvgBtnSelect);
registerIcon('btn-toolbar-plugin', SvgBtnToolbar);
registerIcon('button-plugin', SvgButton);
registerIcon('dropdown-btn-plugin', SvgDropdownBtn);
// 展示类组件 icon x 23
registerIcon('breadcrumb-plugin', SvgBreadcrumb);
registerIcon('card-plugin', SvgCard);
registerIcon('cards-plugin', SvgCards);
registerIcon('carousel-plugin', SvgCarousel);
registerIcon('chart-plugin', SvgChart);
registerIcon('code-plugin', SvgCode);
registerIcon('date-plugin', SvgDate);
registerIcon('datetime-plugin', SvgDatetime);
registerIcon('time-plugin', SvgTime);
registerIcon('image-plugin', SvgImage);
registerIcon('images-plugin', SvgImages);
registerIcon('list-plugin', SvgList);
registerIcon('log-plugin', SvgLog);
registerIcon('mapping-plugin', SvgMapping);
registerIcon('sparkline-plugin', SvgSparkline);
registerIcon('avatar-plugin', SvgAvatar);
registerIcon('progress-plugin', SvgProgress);
registerIcon('json-view-plugin', SvgJsonView);
registerIcon('markdown-plugin', SvgMarkdown);
registerIcon('steps-plugin', SvgSteps);
registerIcon('status-plugin', SvgStatus);
registerIcon('plain-plugin', SvgPlain);
registerIcon('url-plugin', SvgUrl);
// 表单类组件 icon x 53
registerIcon('chained-select-plugin', SvgChainedSelect);
registerIcon('checkbox-plugin', SvgCheckbox);
registerIcon('checkboxes-plugin', SvgCheckboxes);
registerIcon('combo-plugin', SvgCombo);
registerIcon('condition-builder-plugin', SvgConditionBuilder);
registerIcon('diff-editor-plugin', SvgDiffEditor);
registerIcon('editor-plugin', SvgEditor);
registerIcon('hidden-plugin', SvgHidden);
registerIcon('input-city-plugin', SvgInputCity);
registerIcon('input-color-plugin', SvgInputColor);
registerIcon('input-date-range-plugin', SvgInputDateRange);
registerIcon('input-date-plugin', SvgInputDate);
registerIcon('input-datetime-plugin', SvgInputDatetime);
registerIcon('input-email-plugin', SvgInputEmail);
registerIcon('input-excel-plugin', SvgInputExcel);
registerIcon('input-file-plugin', SvgInputFile);
registerIcon('input-group-plugin', SvgInputGroup);
registerIcon('input-image-plugin', SvgInputImage);
registerIcon('input-kv-plugin', SvgInputKv);
registerIcon('input-month-range-plugin', SvgInputMonthRange);
registerIcon('input-number-plugin', SvgInputNumber);
registerIcon('input-password-plugin', SvgInputPassword);
registerIcon('input-quarter-range-plugin', SvgInputQuarterRange);
registerIcon('input-range-plugin', SvgInputRange);
registerIcon('input-rating-plugin', SvgInputRating);
registerIcon('input-repeat-plugin', SvgInputRepeat);
registerIcon('input-rich-text-plugin', SvgInputRichText);
registerIcon('input-tag-plugin', SvgInputTag);
registerIcon('input-text-plugin', SvgInputText);
registerIcon('input-time-range-plugin', SvgInputTimeRange);
registerIcon('input-time-plugin', SvgInputTime);
registerIcon('input-tree-plugin', SvgInputTree);
registerIcon('input-url-plugin', SvgInputUrl);
registerIcon('input-year-plugin', SvgInputYear);
registerIcon('list-select-plugin', SvgListSelect);
registerIcon('location-picker-plugin', SvgLocationPicker);
registerIcon('matrix-checkboxes-plugin', SvgMatrixCheckboxes);
registerIcon('month-plugin', SvgMonth);
registerIcon('nested-select-plugin', SvgNestedSelect);
registerIcon('picker-plugin', SvgPicker);
registerIcon('quarter-plugin', SvgQuarter);
registerIcon('radios-plugin', SvgRadios);
registerIcon('search-box-plugin', SvgSelect);
registerIcon('select-plugin', SvgSelect);
registerIcon('static-plugin', SvgStatic);
registerIcon('sub-form-plugin', SvgSubForm);
registerIcon('switch-plugin', SvgSwitch);
registerIcon('tabs-transfer-plugin', SvgTabsTransfer);
registerIcon('textarea-plugin', SvgTextarea);
registerIcon('transfer-plugin', SvgTransfer);
registerIcon('tree-select-plugin', SvgTreeSelect);
registerIcon('uuid-plugin', SvgUuid);
registerIcon('input-array-plugin', SvgInputArray); // 暂时没用上
registerIcon('formula-plugin', SvgFormula);
// 其他类组件 icon
registerIcon('property-sheet-plugin', SvgPropertySheet);
registerIcon('tooltip-plugin', SvgTooltip);
registerIcon('divider-plugin', SvgDivider);
// 常见布局组件 icon x 13
registerIcon('layout-absolute-plugin', SvgLayoutAbsolute);
registerIcon('layout-fixed-plugin', SvgLayoutFixed);
registerIcon('layout-1with2-plugin', SvgLayout1With2);
registerIcon('layout-2cols-plugin', SvgLayout2Cols);
registerIcon('layout-2row-plugin', SvgLayout2Row);
registerIcon('layout-2with1-plugin', SvgLayout2With1);
registerIcon('layout-3cols-plugin', SvgLayout3Cols);
registerIcon('layout-3row-plugin', SvgLayout3Row);
registerIcon('layout-full-plugin', SvgLayoutFull);
registerIcon('layout-1-2-plugin', SvgLayout12);
registerIcon('layout-2-1-plugin', SvgLayout21);
registerIcon('layout-3-1-plugin', SvgLayout31);
registerIcon('layout-3-2-plugin', SvgLayout32);
registerIcon('layout-free-container', SvgLayoutFreeContainer);
registerIcon('layout-fixed-top', SvgLayoutFixedTop);
registerIcon('input-add-fx', SvgFx);
registerIcon('input-fx', SvgFx$1);
// 属性配置面板/显示类型
registerIcon('inline-display', SvgInline);
registerIcon('inline-block-display', SvgInlineBlock);
registerIcon('block-display', SvgBlock);
registerIcon('flex-display', SvgFlex);
// 属性配置面板/flex相关配置icon
registerIcon('drow', SvgDrow);
registerIcon('dcolumn', SvgDcolumn);
registerIcon('drowReverse', SvgDrowReverse);
registerIcon('dcolumnReverse', SvgDcolumnReverse);
registerIcon('aFlexStart', SvgAFlexStart);
registerIcon('aCenter', SvgACenter);
registerIcon('aFlexEnd', SvgAFlexEnd);
registerIcon('aStretch', SvgAStretch);
registerIcon('aBaseline', SvgABaseline);
registerIcon('jFlexStart', SvgJFlexStart);
registerIcon('jCenter', SvgJCenter);
registerIcon('jFlexEnd', SvgJFlexEnd);
registerIcon('jSpaceBetween', SvgJSpaceBetween);
registerIcon('jSpaceAround', SvgJSpaceAround);
// 主题
registerIcon('theme-css', SvgCss);
// CRUD相关
registerIcon('column-setting', SvgColumnSetting);
registerIcon('column-delete', SvgColumnDelete);
registerIcon('column-add', SvgColumnAdd);
registerIcon('share-link', SvgShareLink);
window.amisEditorVersionInfo={version:'1.1.2',buildTime:'2023-10-27'};
